django_web_app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('', user_views.main_home, name='main_home'),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('files_share.urls')),
    path('password/', include('password_manager.urls')),
    path('encrypt_decrypt/', include('encrypt_decrypt.urls')),
    path('todo/', include('todo.urls')),
    path('url/', include('url_shortner.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

password_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.home, name="password"),

    path('new/', login_required(LocationCreateView.as_view()), name='create-pass'),
    
    path("view/<str:pk>/", views.view, name = "view-pass"),
]

todo/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from . import views

urlpatterns=[
  path('', login_required(views.Index.as_view()), name="index"),
  path('delete/<int:pk>/', login_required(views.Delete.as_view()), name="delete"),
  path('update/<int:pk>/', login_required(views.Update.as_view()), name="update"),
  path('complete/<int:pk>/', login_required(views.complete), name="complete"),
]

password_manager/models.py
from django.db import models
from users.models import User
from django.urls import reverse
# Create your models here.

class Location(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    
    website_name = models.CharField(max_length=50)
    website_link = models.URLField(max_length=200, null=True)
    website_username = models.CharField(max_length=50)
    website_password = models.CharField(max_length=50)
    website_notes = models.CharField( max_length=50, null=True)
    master_password = models.CharField(max_length=200, default='')

    created = models.DateTimeField( auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.website_name

    def get_absolute_url(self):
        return reverse("password")
    

password_manager/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Location
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from django.contrib.auth.hashers import check_password
from .encryption import *

# Create your views here.
@login_required
def home(request):
    user = request.user
    location = Location.objects.filter(author = user)
    context = {
        'location': location
    }
    return render(request, "main/home.html", context)

class LocationCreateView(CreateView):
    template_name = 'main/location_form.html'
    model = Location
    fields = [
        'website_name',
        'website_link',
        'website_username',
        'website_password',
        'website_notes',
        'master_password',
    ]

    def form_valid(self, form):
        if form.is_valid():
            user = self.request.user
            form.instance.author = user

            form_master_password = form.instance.master_password
            # the field titled "master_password" in Location model 

            user_password = self.request.user.password
            # hashed master password in database 

            if not check_password(form_master_password, user_password):
                messages.add_message(self.request, messages.ERROR, 'Wrong Master Password')
                return redirect("create-pass")
            else: 
                website_password = form.instance.website_password

                form.instance.website_password = encrypt(form_master_password.encode(), website_password.encode())

                form.instance.website_password = encrypt(form_master_password.encode(), form.instance.website_password.encode())
                # to encrypt twice

                form.instance.master_password = ''
                # Clears out "master_password" of Location so that it isn't stored database 
                # If not, it will be stored as plain text
                # Storing plain text passwords has to be avoided at all costs
                
                return super().form_valid(form)
        else:
            messages.error(self.request, "Error")
            messages.add_message(self.request, messages.ERROR, 'Error')


@login_required
def view(request, pk):
    user = request.user
    location = Location.objects.get(id=pk, author=user)
    message = ''
    if request.method =="POST":
        user_password = location.website_password
        password = request.POST.get("password_field")
        if decrypted := decrypt(password.encode(), user_password):
            decrypted = decrypt(password.encode(), decrypted)
            context = {
                'location': location,
                'decrypted': decrypted,
                'confirmed': True, # user provided the right password
            }
            return render(request, "main/detail_view.html", context)
        else:
            message = 'try again'
    
    context = {
        'location': location,
        'message': message,
    }

    return render(request, "main/detail_view.html", context)

password_manager/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="secure password manager.">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >
    <link rel="stylesheet" href="{% static 'blog/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Password Manager</title>

</head>
<body style="text-align: center; font-family: 'Oxanium';">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand  display-1" href="{% url 'main_home' %}">Password Manager</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link font-weight-light" href="{% url 'password' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                </ul>

                {% if user.is_authenticated %}
                <a href="{% url 'create-pass' %} " class="btn text-white m-2"><i class="fas fa-user-edit"></i> Add Password</a>
                <a href="{% url 'profile' %} " class="btn text-white m-2"><i class="fas fa-user"></i> {{ user.username }}</a>
                <a href="{% url 'logout' %} " class="btn text-white m-2"><i class="fas fa-sign-out-alt"></i> Log Out</a>
                
                {% else %}
                <a href="{% url 'login' %} " class="btn text-white m-2"><i class="fas fa-user-tie"></i> Login</a>
                
                <a href="{% url 'register' %} " class="btn text-white m-2"> <i class="fas fa-sign-in-alt"></i> Sign Up</a>
                {% endif %}
            </div>
        </nav>
    <main>
        <section>
        <br/>
        {% block content %}{% endblock  %}
        </section>
    </main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="{% static 'blog/main.js' %}"></script>
</body>
</html>

password_manager/templates/main/detail_view.html
{%extends "main/base.html"%}
{% load static %}

{%block content%}
    <div class="div-container">
        <div>
            <h2 class = "main-color" style="display:inline; position: relative;text-align: left">Name: </h2><h2 style="display:inline; word-wrap: break-word">{{location}}</h2>
        </div>
        <div>
            <br/>
            <h3 class = "main-color" style="display:inline;">Link: </h3><h3 style="display:inline; word-wrap: break-word">{{location.website_link}}</h3>
        </div>
        <div>
            <br/>
            <h2 class = "main-color" style="display:inline;">Username: </h2><h2 style="display:inline; word-wrap: break-word">{{location.website_username}}</h2>
        </div>
        <div>
            <br/>
            <h2 class = "main-color" style="display:inline;">Notes: </h2><h2 style="display:inline; word-wrap: break-word">{{location.website_notes}}</h2>
        </div>
        <div>
            {% if not confirmed%}
                <form method = "POST">
                    {% csrf_token %}
                    <h2 class = "main-color">Provide master password to view {{location}} password:</h2>

                    <input type="password" name = "password_field" name="Password">

                    <input type="submit" value="Submit">
                </form>
            {% endif %}
            <div>
                {% if confirmed %}
                    <br/>
                    <h2 class = "main-color" style="display:inline;">Password: </h2>
                    <h2 style="display:inline; word-wrap: break-word">{{decrypted}}</h2>
                {% else %}
                    <h2>{{message}}</h2>
                {% endif %}
            </div>
        </div>
    </div>
{%endblock content%}

password_manager/templates/main/home.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
    {% for message in messages %}
        <div class="div-container">
            <h1>{{message}}</h1>
        </div>
        <br />
        <br />
    {% endfor %}
    {% if location %}
        {% for row in location %}
            <div class = "div-container">
                <h1 style="text-align: center; font-size:40px;color:black"><a class='link' href = "{% url 'view-pass' row.id %}">{{row}}</a></h1>
            </div>
            <br/>
            <br/>
        {% endfor %}
    {% else %}
        <h1 style="text-align: center; font-size:40px"><a class='link' href = "{% url 'create-pass' %}">Store Your First Password!</a></h1>
    {% endif %}
{% endblock %}

password_manager/templates/main/location_form.html
{%extends "main/base.html"%}
{% load static %}

{%block content%}
    {% for message in messages %}
        <div class="div-container">
            <h1>{{message}}</h1>
        </div>
        <br />
        <br />
    {% endfor %}

    <form method="POST">
        {% csrf_token %}
        <div class = "div-container">
            <p class = "main-color">
                <p><label for="id_website_name">Website name:</label> <input type="text"    name="website_name" maxlength="50" required id="id_website_name"></p>

                <p><label for="id_website_link">Website link:</label> <input type="url"         name="website_link" maxlength="180" required id="id_website_link"></p>

                <p><label for="id_website_username">Website username:</label> <input type="text"        name="website_username" maxlength="50" required id="id_website_username"></p>

                <p><label for="id_website_password">Website password:</label> <input type="password"        name="website_password" maxlength="50" required id="id_website_password"></p>

                <p><label for="id_website_notes">Website notes:</label> <input type="text"      name="website_notes" maxlength="50" required id="id_website_notes"></p>

                <p><label for="id_master_password">Master password:</label> <input type="password"      name="master_password" maxlength="55" required id="id_master_password"></p>
                <input style = "border-radius:10px;"type="submit" value="Submit">
            </p>
        </div>
    </form>
{%endblock content%}